Save and find nested entities
herbsjs/herbs2mongo pull request #37
Opened 2023-07-10 01:44 UTC by vitorgamer58

This pull request aims to implement a feature that will allow inserting and finding entities that contain fields that are entities (or array of entities), which in this context, I called nested entities.
This is related to issue #35
I also added export DataMapper class in Herbs2Mongo.js to allow developer to extend this class and create their own custom DataMapper.
I'm already covering a previous case reported in the issue, in which the collection was missing in the database containing the `meta` field that is inherited from BaseEntity, however, I'm not covering the `errors` field, which for now can be covered by developers simply doing a delete on the object before calling the find method, as this is a feature that will be addressed in the issue: https://github.com/herbsjs/gotu/issues/71
These changes do not implement breaking changes.

## Proposed Changes

1. [Adjusts collectionFieldsWithValues method to work with nested entities](https://github.com/herbsjs/herbs2mongo/commit/d62cb04653e6e76a567df3eb100507654aab546e)
2. [Adjusts collectionFields method to not remove entities](https://github.com/herbsjs/herbs2mongo/commit/d62cb04653e6e76a567df3eb100507654aab546e)
3. [Adjust buildProxy to not return undefined when isEntity is true](https://github.com/herbsjs/herbs2mongo/commit/68dfcf031812f65989f71a8b8aad46f2778abd3b)
4. [Improved empty object checking in arrayDataParse](https://github.com/herbsjs/herbs2mongo/commit/2453cb72df917923f8ca668f1fe40890e8c0c2dc)
5. [Enable export of DataMapper class](https://github.com/herbsjs/herbs2mongo/commit/e34049e124aee6b660b28574d530cb3bdf29eed4)

## Screenshots
Nested entity in find method return:
![Find](https://github.com/herbsjs/herbs2mongo/assets/8906065/217abde0-a0a6-4f0b-a581-03c3e2c23afd)
Nested entity that was saved to the database:
![MongoDB Compass](https://github.com/herbsjs/herbs2mongo/assets/8906065/aaf04889-b073-4020-8030-678f346f239e)

## Readiness Checklist

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2023-07-10 12:31 UTC, programadriano commented on src/dataMapper.js
> +    if (instance[i.name] === null || instance[i.name] === undefined) return null
O checker.isEmpty não funcionaria aqui?

2023-07-10 13:32 UTC, vitorgamer58 commented on src/dataMapper.js
> +    if (instance[i.name] === null || instance[i.name] === undefined) return null
Funcionaria, inclusive desenvolvi inicialmente usando o isEmpty, mas isso implementaria uma breaking change, pois o isEmpty entende um objeto vazio `{}` como vazio, e portanto, não salvaria no banco de dados.
Então algum sistema que hoje em dia esteja salvando um objeto vazio, deixaria de salvar, o que é uma breaking change, pois onde eu pesquisaria por objeto vazio, teria que ser alterado para pesquisar por objeto vazio ou null.
Para evitar a implementação de breaking change, preferi manter o comportamento da maneira que é feito hoje.

2023-07-10 13:35 UTC, jhomarolo requested changes
Please add tests in testDB folder before the full review

2023-07-12 00:53 UTC, vitorgamer58 commented
> Please add tests in testDB folder before the full review

Valid, added tests referring to nested entities in the findById file.

2023-08-20 16:33 UTC, dalssoft approved these changes

2023-08-22 12:54 UTC, merged